---
output: word_document
---

```{r, include=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)

library(tidyverse)
library(kableExtra)
library(gtsummary)
library(huxtable)

sims <- read_rds("../data/01_simulated_data.rds") %>%
  slice(1) %>%
  unnest(df) %>%
  select(id, female, age, measured_diff, brain_volume, pwv_visit1_measured, pwv_visit2_measured) %>%
  mutate(diff_grouped  = Hmisc::cut2(round(measured_diff, 1), g = 3))

sims_updated <- Hmisc::upData(sims,
                              labels = list("female" = "Female",
                                            "age" = "Age (years)",
                                            "brain_volume" = "Brain volume (cm^3)",
                                            "pwv_visit1_measured" = "PWV at visit 1 (measured)",
                                            "pwv_visit2_measured" = "PWV at visit 2 (measured)",
                                            "diff_grouped" = "Change in PWV between visits 1 and 2")
                              )
```

```{r}
sims_updated %>%
  select(-measured_diff, -id, -age) %>%
  tbl_summary(
    by = "diff_grouped"
  ) %>%
  as_flex_table()
```

